"""Write a safe `.env` for the Docker stack.

    python deploy/make_env.py --demo      # no accounts needed: password-gated demo sign-in
    python deploy/make_env.py             # real deployment: you fill in Supabase afterwards

It never overwrites an existing `.env` (use --force). Secrets are generated with
`secrets.token_urlsafe`, so every machine gets its own.
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build_env(demo: bool) -> tuple[str, str | None]:
    secret = secrets.token_urlsafe(48)
    lines = [
        '# Generated by deploy/make_env.py',
        'APP_ENV=production',
        f'JWT_SECRET_KEY={secret}',
        'TRUST_PROXY_HEADERS=true',
        'RATE_LIMIT_ENABLED=true',
        '',
    ]
    password = None
    if demo:
        password = secrets.token_urlsafe(12)
        lines += [
            '# Demo mode: no identity provider. Everyone signs in with this shared password,',
            '# using one of analyst@local, soc@local, admin@local, researcher@local.',
            '# Do not use with real data.',
            'ALLOW_DEV_LOGIN=true',
            f'DEV_LOGIN_PASSWORD={password}',
        ]
    else:
        lines += [
            '# Fill these in (see supabase/README.md), then restart the stack.',
            'SUPABASE_URL=',
            'SUPABASE_SERVICE_KEY=',
        ]
    lines += ['', '# Optional integrations: see .env.example for VIRUSTOTAL_API_KEY, SMTP_*, SIEM_WEBHOOK_*', '']
    return '\n'.join(lines), password


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--demo', action='store_true', help='password-gated demo sign-in (no accounts)')
    parser.add_argument('--force', action='store_true', help='overwrite an existing .env')
    parser.add_argument('--out', default=str(ROOT / '.env'))
    args = parser.parse_args()

    out = Path(args.out)
    if out.exists() and not args.force:
        print(f'{out} already exists; not overwriting (use --force).')
        return 1
    content, password = build_env(args.demo)
    out.write_text(content, encoding='utf-8')
    print(f'Wrote {out}')
    if password:
        print(f'Demo sign-in password: {password}')
        print('Accounts: analyst@local, soc@local, admin@local, researcher@local')
    return 0


if __name__ == '__main__':
    sys.exit(main())
